name: Run UI Checks

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@86e7197484018ef6aaa9255d186f6ce1754276dd # 1.97.0

      - name: Install native dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev librsvg2-dev

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run type check
        run: yarn run tsc:check

      - name: Run lint check
        run: yarn run lint:check

      - name: Run format check
        run: yarn run format:check

      - name: Run frontend tests
        run: yarn run test

      - name: Build frontend
        run: yarn run build

      - name: Run Rust tests
        run: cargo test --locked --manifest-path src-tauri/Cargo.toml

      - name: Audit Rust dependencies
        uses: rustsec/audit-check@858dc40f52ca2b8570b7a997c1c4e35c6fc9a432 # Node 24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: src-tauri
