name: Build Windows Preview

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: windows-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: yarn

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@86e7197484018ef6aaa9255d186f6ce1754276dd # 1.97.0

      - name: Rust cache
        uses: swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: yarn install --immutable

      - name: Build Preview app
        run: yarn tauri build --config src-tauri/tauri.preview.conf.json --no-bundle -- --locked

      - name: Upload Windows Preview
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Tauthy-Preview-Windows
          path: 'src-tauri/target/release/Tauthy Preview.exe'
          if-no-files-found: error
          retention-days: 14
